# Copyright (c) 2026, tephpy Contributors.
#
# This file is part of tephpy and is distributed under the 3-Clause BSD license.
# See the LICENSE file in the package root directory for licensing details.

"""Publish an estimated reading time on a documentation page (reading spec §3.2).

The count comes from the parsed doctree rather than from the page source, so
directive options, comment blocks and MyST front matter are not counted as
words a reader reads, and a page body generated by another directive is
(reading spec §3.3). That is why the work happens on ``doctree-read`` and not
in ``run()``: the directive returns a placeholder, and the handler below fills
it in once the document it is measuring exists.

The rate, the word pattern and the argument grammar live in ``tephpy_reading``,
which the gate of reading spec §3.6 imports too. Keeping them there is what makes
them testable: the CI test matrix has no Sphinx.

Notes
-----
.. versionadded:: 0.1.0

"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from docutils import nodes
from sphinx.util.docutils import SphinxDirective
import tephpy_reading

if TYPE_CHECKING:
    from sphinx.application import Sphinx

SKIP = (nodes.system_message, nodes.comment, nodes.raw)
"""Doctree text a reader never reads (reading spec §3.3)."""

ICON = '<i class="fa-solid fa-clock"></i>'
"""The clock, as pydata-sphinx-theme's own markup for a Font Awesome glyph.

Raw HTML rather than a CSS ``::before`` glyph, because the CSS route would need
``font-family: "Font Awesome 7 Free"`` written into this project's stylesheet and
would break silently on a theme upgrade to Font Awesome 8. The theme emits this
same element throughout the built site, so it costs no assets (reading spec §3.5).
"""


class readingtime(nodes.Element):  # noqa: N801
    """A placeholder standing where the banner goes until the document is parsed.

    Deliberately **not** registered with ``app.add_node``. If the handler below
    ever fails to fire, Sphinx reports ``unknown node type`` and exits non-zero,
    which ``--fail-on-warning`` turns into a build failure -- where a registered
    node would publish a blank space quietly (reading spec §3.2).

    Notes
    -----
    .. versionadded:: 0.1.0

    """


class ReadingTimeDirective(SphinxDirective):
    """Emit a reading-time banner for the page it appears on.

    Notes
    -----
    .. versionadded:: 0.1.0

    """

    has_content = False
    optional_arguments = 1
    final_argument_whitespace = False

    def run(self) -> list[nodes.Node]:
        """Return the placeholder the ``doctree-read`` handler resolves.

        Returns
        -------
        list of docutils.nodes.Node
            A single unresolved :class:`readingtime` element.

        Raises
        ------
        docutils.parsers.rst.states.MarkupError
            When the argument matches neither documented shape.

        Notes
        -----
        .. versionadded:: 0.1.0

        """
        argument = self.arguments[0] if self.arguments else None
        try:
            parsed = tephpy_reading.parse_argument(argument)
        except ValueError as error:
            raise self.error(str(error)) from error
        return [readingtime(minutes=parsed.minutes, wpm=parsed.wpm)]


def count_doctree_words(doctree: nodes.document) -> int:
    """Count the words a reader reads on the parsed page.

    Parameters
    ----------
    doctree : docutils.nodes.document
        The parsed document.

    Returns
    -------
    int
        The words in every text node not descended from :data:`SKIP`.

    Notes
    -----
    .. versionadded:: 0.1.0

    """
    total = 0
    for text in doctree.findall(nodes.Text):
        node = text.parent
        while node is not None and not isinstance(node, SKIP):
            node = node.parent
        if node is None:
            total += tephpy_reading.count_words(text.astext())
    return total


def banner(minutes: int) -> nodes.container:
    """Build the banner for a page of ``minutes`` minutes.

    Parameters
    ----------
    minutes : int
        The estimate to publish.

    Returns
    -------
    docutils.nodes.container
        Real docutils nodes rather than a raw HTML block, so a non-HTML builder
        and text extraction both see the estimate (reading spec §3.5).

    Notes
    -----
    .. versionadded:: 0.1.0

    """
    plural = "" if minutes == 1 else "s"
    paragraph = nodes.paragraph()
    paragraph += nodes.raw("", ICON, format="html")
    paragraph += nodes.Text(f" Estimated reading time: {minutes} minute{plural}")
    container = nodes.container(classes=["reading-time"])
    container += paragraph
    return container


def resolve(app: Sphinx, doctree: nodes.document) -> None:  # noqa: ARG001
    """Replace each placeholder on this page with its banner.

    Parameters
    ----------
    app : sphinx.application.Sphinx
        The application. Unread: the count is a property of the page alone.
    doctree : docutils.nodes.document
        The parsed document, counted once however many placeholders it carries.

    Notes
    -----
    .. versionadded:: 0.1.0

    """
    placeholders = list(doctree.findall(readingtime))
    if not placeholders:
        return
    words = count_doctree_words(doctree)
    for node in placeholders:
        minutes = node["minutes"]
        if minutes is None:
            minutes = tephpy_reading.estimate_minutes(words, node["wpm"])
        node.replace_self(banner(minutes))


def setup(app: Sphinx) -> dict[str, Any]:
    """Register the directive and its transform.

    Parameters
    ----------
    app : sphinx.application.Sphinx
        The application.

    Returns
    -------
    dict
        The extension metadata.

    Notes
    -----
    .. versionadded:: 0.1.0

    """
    app.add_directive("readingtime", ReadingTimeDirective)
    app.connect("doctree-read", resolve)
    return {
        "version": "0.1.0",
        "parallel_read_safe": True,
        "parallel_write_safe": True,
    }
